export const citiesPR = [
  { slug: 'curitiba', name: 'Curitiba' },
  { slug: 'abatia', name: 'Abatia' },
  { slug: 'adrianopolis', name: 'Adrianopolis' },
  { slug: 'agudos-do-sul', name: 'Agudos Do Sul' },
  { slug: 'almirante-tamandare', name: 'Almirante Tamandare' },
  { slug: 'altamira-do-parana', name: 'Altamira Do Parana' },
  { slug: 'alto-paraiso', name: 'Alto Paraiso' },
  { slug: 'alto-parana', name: 'Alto Parana' },
  { slug: 'alto-piquiri', name: 'Alto Piquiri' },
  { slug: 'altonia', name: 'Altonia' },
  { slug: 'alvorada-do-sul', name: 'Alvorada Do Sul' },
  { slug: 'amapora', name: 'Amapora' },
  { slug: 'ampere', name: 'Ampere' },
  { slug: 'anahy', name: 'Anahy' },
  { slug: 'andira', name: 'Andira' },
  { slug: 'angulo', name: 'Angulo' },
  { slug: 'antonina', name: 'Antonina' },
  { slug: 'antonina-capanema', name: 'Antonina Capanema' },
  { slug: 'antonio-olinto', name: 'Antonio Olinto' },
  { slug: 'apucarana', name: 'Apucarana' },
  { slug: 'arapongas', name: 'Arapongas' },
  { slug: 'arapoti', name: 'Arapoti' },
  { slug: 'arapua', name: 'Arapua' },
  { slug: 'araruna', name: 'Araruna' },
  { slug: 'araucaria', name: 'Araucaria' },
  { slug: 'ariranha-do-ivai', name: 'Ariranha Do Ivai' },
  { slug: 'assai', name: 'Assai' },
  { slug: 'assis-chateaubriand', name: 'Assis Chateaubriand' },
  { slug: 'astorga', name: 'Astorga' },
  { slug: 'atalaia', name: 'Atalaia' },
  { slug: 'balsa-nova', name: 'Balsa Nova' },
  { slug: 'bandeirantes', name: 'Bandeirantes' },
  { slug: 'barbosa-ferraz', name: 'Barbosa Ferraz' },
  { slug: 'barra-do-jacare', name: 'Barra Do Jacare' },
  { slug: 'barracao', name: 'Barracao' },
  { slug: 'bela-vista-da-caroba', name: 'Bela Vista Da Caroba' },
  { slug: 'bela-vista-do-paraiso', name: 'Bela Vista Do Paraiso' },
  { slug: 'bituruna', name: 'Bituruna' },
  { slug: 'boa-esperanca', name: 'Boa Esperanca' },
  { slug: 'boa-esperanca-do-iguacu', name: 'Boa Esperanca Do Iguacu' },
  { slug: 'boa-ventura-de-sao-roque', name: 'Boa Ventura De Sao Roque' },
  { slug: 'boa-vista-da-aparecida', name: 'Boa Vista Da Aparecida' },
  { slug: 'bocaiuva-do-sul', name: 'Bocaiuva Do Sul' },
  { slug: 'bom-jesus-do-sul', name: 'Bom Jesus Do Sul' },
  { slug: 'bom-sucesso', name: 'Bom Sucesso' },
  { slug: 'bom-sucesso-do-sul', name: 'Bom Sucesso Do Sul' },
  { slug: 'borrazopolis', name: 'Borrazopolis' },
  { slug: 'braganey', name: 'Braganey' },
  { slug: 'brasilandia-do-sul', name: 'Brasilandia Do Sul' },
  { slug: 'buturana', name: 'Buturana' },
  { slug: 'cafeara', name: 'Cafeara' },
  { slug: 'cafelandia', name: 'Cafelandia' },
  { slug: 'cafezal-do-sul', name: 'Cafezal Do Sul' },
  { slug: 'california', name: 'California' },
  { slug: 'cambara', name: 'Cambara' },
  { slug: 'cambe', name: 'Cambe' },
  { slug: 'cambira', name: 'Cambira' },
  { slug: 'campina-da-lagoa', name: 'Campina Da Lagoa' },
  { slug: 'campina-do-simao', name: 'Campina Do Simao' },
  { slug: 'campina-grande-do-sul', name: 'Campina Grande Do Sul' },
  { slug: 'campo-bonito', name: 'Campo Bonito' },
  { slug: 'campo-do-tenente', name: 'Campo Do Tenente' },
  { slug: 'campo-largo', name: 'Campo Largo' },
  { slug: 'campo-magro', name: 'Campo Magro' },
  { slug: 'campo-mourao', name: 'Campo Mourao' },
  { slug: 'candido-de-abreu', name: 'Candido De Abreu' },
  { slug: 'candoi', name: 'Candoi' },
  { slug: 'cantagalo', name: 'Cantagalo' },
  { slug: 'capanema', name: 'Capanema' },
  { slug: 'capitao-leonidas-marques', name: 'Capitao Leonidas Marques' },
  { slug: 'carambei', name: 'Carambei' },
  { slug: 'carlopolis', name: 'Carlopolis' },
  { slug: 'cascavel', name: 'Cascavel' },
  { slug: 'castro', name: 'Castro' },
  { slug: 'catanduvas', name: 'Catanduvas' },
  { slug: 'centenario-do-sul', name: 'Centenario Do Sul' },
  { slug: 'cerro-azul', name: 'Cerro Azul' },
  { slug: 'ceu-azul', name: 'Ceu Azul' },
  { slug: 'chopinzinho', name: 'Chopinzinho' },
  { slug: 'cianorte', name: 'Cianorte' },
  { slug: 'cidade-gaucha', name: 'Cidade Gaucha' },
  { slug: 'clevelandia', name: 'Clevelandia' },
  { slug: 'colombo', name: 'Colombo' },
  { slug: 'colorado', name: 'Colorado' },
  { slug: 'congonhinhas', name: 'Congonhinhas' },
  { slug: 'conselheiro-mairinck', name: 'Conselheiro Mairinck' },
  { slug: 'contenda', name: 'Contenda' },
  { slug: 'corbelia', name: 'Corbelia' },
  { slug: 'cornelio-procopio', name: 'Cornelio Procopio' },
  { slug: 'coronel-domingos-soares', name: 'Coronel Domingos Soares' },
  { slug: 'coronel-vivida', name: 'Coronel Vivida' },
  { slug: 'corumbatai-do-sul', name: 'Corumbatai Do Sul' },
  { slug: 'cruz-machado', name: 'Cruz Machado' },
  { slug: 'cruzeiro-do-iguacu', name: 'Cruzeiro Do Iguacu' },
  { slug: 'cruzeiro-do-oeste', name: 'Cruzeiro Do Oeste' },
  { slug: 'cruzeiro-do-sul', name: 'Cruzeiro Do Sul' },
  { slug: 'cruzmaltina', name: 'Cruzmaltina' },
  { slug: 'curiuva', name: 'Curiuva' },
  { slug: 'diamante-d-oeste', name: 'Diamante D Oeste' },
  { slug: 'diamante-do-norte', name: 'Diamante Do Norte' },
  { slug: 'diamante-do-sul', name: 'Diamante Do Sul' },
  { slug: 'dois-vizinhos', name: 'Dois Vizinhos' },
  { slug: 'douradina', name: 'Douradina' },
  { slug: 'doutor-camargo', name: 'Doutor Camargo' },
  { slug: 'doutor-ulysses', name: 'Doutor Ulysses' },
  { slug: 'eneas-marques', name: 'Eneas Marques' },
  { slug: 'engenheiro-beltrao', name: 'Engenheiro Beltrao' },
  { slug: 'entre-rios-do-oeste', name: 'Entre Rios Do Oeste' },
  { slug: 'esperanca-nova', name: 'Esperanca Nova' },
  { slug: 'espigao-alto-do-iguacu', name: 'Espigao Alto Do Iguacu' },
  { slug: 'farol', name: 'Farol' },
  { slug: 'faxinal', name: 'Faxinal' },
  { slug: 'fazenda-rio-grande', name: 'Fazenda Rio Grande' },
  { slug: 'fenix', name: 'Fenix' },
  { slug: 'fernandes-pinheiro', name: 'Fernandes Pinheiro' },
  { slug: 'figueira', name: 'Figueira' },
  { slug: 'flor-da-serra-do-sul', name: 'Flor Da Serra Do Sul' },
  { slug: 'florai', name: 'Florai' },
  { slug: 'floresta', name: 'Floresta' },
  { slug: 'florestopolis', name: 'Florestopolis' },
  { slug: 'florida', name: 'Florida' },
  { slug: 'formosa-do-oeste', name: 'Formosa Do Oeste' },
  { slug: 'foz-do-iguacu', name: 'Foz Do Iguacu' },
  { slug: 'foz-do-jordao', name: 'Foz Do Jordao' },
  { slug: 'francisco-alves', name: 'Francisco Alves' },
  { slug: 'francisco-beltrao', name: 'Francisco Beltrao' },
  { slug: 'general-carneiro', name: 'General Carneiro' },
  { slug: 'godoy-moreira', name: 'Godoy Moreira' },
  { slug: 'goioere', name: 'Goioere' },
  { slug: 'goioxim', name: 'Goioxim' },
  { slug: 'grandes-rios', name: 'Grandes Rios' },
  { slug: 'guaira', name: 'Guaira' },
  { slug: 'guairaca', name: 'Guairaca' },
  { slug: 'guamiranga', name: 'Guamiranga' },
  { slug: 'guapirama', name: 'Guapirama' },
  { slug: 'guaporema', name: 'Guaporema' },
  { slug: 'guaraci', name: 'Guaraci' },
  { slug: 'guaraniacu', name: 'Guaraniacu' },
  { slug: 'guarapuava', name: 'Guarapuava' },
  { slug: 'guaraquecaba', name: 'Guaraquecaba' },
  { slug: 'guaratuba', name: 'Guaratuba' },
  { slug: 'honorio-serpa', name: 'Honorio Serpa' },
  { slug: 'ibaiti', name: 'Ibaiti' },
  { slug: 'ibema', name: 'Ibema' },
  { slug: 'ibipora', name: 'Ibipora' },
  { slug: 'icaraima', name: 'Icaraima' },
  { slug: 'iguaracu', name: 'Iguaracu' },
  { slug: 'iguatu', name: 'Iguatu' },
  { slug: 'imbau', name: 'Imbau' },
  { slug: 'imbituva', name: 'Imbituva' },
  { slug: 'inacio-martins', name: 'Inacio Martins' },
  { slug: 'inaja', name: 'Inaja' },
  { slug: 'indianopolis', name: 'Indianopolis' },
  { slug: 'ipiranga', name: 'Ipiranga' },
  { slug: 'ipora', name: 'Ipora' },
  { slug: 'iracema-do-oeste', name: 'Iracema Do Oeste' },
  { slug: 'irati', name: 'Irati' },
  { slug: 'iretama', name: 'Iretama' },
  { slug: 'itaguaje', name: 'Itaguaje' },
  { slug: 'itaipulandia', name: 'Itaipulandia' },
  { slug: 'itambaraca', name: 'Itambaraca' },
  { slug: 'itambe', name: 'Itambe' },
  { slug: 'itapejara-d-oeste', name: 'Itapejara D Oeste' },
  { slug: 'itaperucu', name: 'Itaperucu' },
  { slug: 'itauna-do-sul', name: 'Itauna Do Sul' },
  { slug: 'ivai', name: 'Ivai' },
  { slug: 'ivaipora', name: 'Ivaipora' },
  { slug: 'ivate', name: 'Ivate' },
  { slug: 'ivatuba', name: 'Ivatuba' },
  { slug: 'jaboti', name: 'Jaboti' },
  { slug: 'jacarezinho', name: 'Jacarezinho' },
  { slug: 'jaguapita', name: 'Jaguapita' },
  { slug: 'jaguariaiva', name: 'Jaguariaiva' },
  { slug: 'jandaia-do-sul', name: 'Jandaia Do Sul' },
  { slug: 'janiopolis', name: 'Janiopolis' },
  { slug: 'japira', name: 'Japira' },
  { slug: 'japura', name: 'Japura' },
  { slug: 'jardim-alegre', name: 'Jardim Alegre' },
  { slug: 'jardim-olinda', name: 'Jardim Olinda' },
  { slug: 'jataizinho', name: 'Jataizinho' },
  { slug: 'jesuitas', name: 'Jesuitas' },
  { slug: 'joaquim-tavora', name: 'Joaquim Tavora' },
  { slug: 'jundiai-do-sul', name: 'Jundiai Do Sul' },
  { slug: 'juranda', name: 'Juranda' },
  { slug: 'jussara', name: 'Jussara' },
  { slug: 'kalore', name: 'Kalore' },
  { slug: 'lapa', name: 'Lapa' },
  { slug: 'laranjal', name: 'Laranjal' },
  { slug: 'laranjeiras-do-sul', name: 'Laranjeiras Do Sul' },
  { slug: 'leopolis', name: 'Leopolis' },
  { slug: 'lidianopolis', name: 'Lidianopolis' },
  { slug: 'lindoeste', name: 'Lindoeste' },
  { slug: 'loanda', name: 'Loanda' },
  { slug: 'lobato', name: 'Lobato' },
  { slug: 'londrina', name: 'Londrina' },
  { slug: 'luiziana', name: 'Luiziana' },
  { slug: 'lunardelli', name: 'Lunardelli' },
  { slug: 'lupionopolis', name: 'Lupionopolis' },
  { slug: 'mallet', name: 'Mallet' },
  { slug: 'mambore', name: 'Mambore' },
  { slug: 'mandaguacu', name: 'Mandaguacu' },
  { slug: 'mandaguari', name: 'Mandaguari' },
  { slug: 'mandirituba', name: 'Mandirituba' },
  { slug: 'manfrinopolis', name: 'Manfrinopolis' },
  { slug: 'mangueirinha', name: 'Mangueirinha' },
  { slug: 'manoel-ribas', name: 'Manoel Ribas' },
  { slug: 'marechal-candido-rondon', name: 'Marechal Candido Rondon' },
  { slug: 'maria-helena', name: 'Maria Helena' },
  { slug: 'marialva', name: 'Marialva' },
  { slug: 'marilandia-do-sul', name: 'Marilandia Do Sul' },
  { slug: 'marilena', name: 'Marilena' },
  { slug: 'mariluz', name: 'Mariluz' },
  { slug: 'maringa', name: 'Maringa' },
  { slug: 'mariopolis', name: 'Mariopolis' },
  { slug: 'maripa', name: 'Maripa' },
  { slug: 'marmeleiro', name: 'Marmeleiro' },
  { slug: 'marquinho', name: 'Marquinho' },
  { slug: 'marumbi', name: 'Marumbi' },
  { slug: 'matelandia', name: 'Matelandia' },
  { slug: 'matinhos', name: 'Matinhos' },
  { slug: 'mato-rico', name: 'Mato Rico' },
  { slug: 'maua-da-serra', name: 'Maua Da Serra' },
  { slug: 'medianeira', name: 'Medianeira' },
  { slug: 'mercedes', name: 'Mercedes' },
  { slug: 'mirador', name: 'Mirador' },
  { slug: 'miraselva', name: 'Miraselva' },
  { slug: 'missal', name: 'Missal' },
  { slug: 'moreira-sales', name: 'Moreira Sales' },
  { slug: 'morretes', name: 'Morretes' },
  { slug: 'munhoz-de-melo', name: 'Munhoz De Melo' },
  { slug: 'nossa-senhora-das-gracas', name: 'Nossa Senhora Das Gracas' },
  { slug: 'nova-alianca-do-ivai', name: 'Nova Alianca Do Ivai' },
  { slug: 'nova-america-da-colina', name: 'Nova America Da Colina' },
  { slug: 'nova-aurora', name: 'Nova Aurora' },
  { slug: 'nova-cantu', name: 'Nova Cantu' },
  { slug: 'nova-esperanca', name: 'Nova Esperanca' },
  { slug: 'nova-esperanca-do-sudoeste', name: 'Nova Esperanca Do Sudoeste' },
  { slug: 'nova-fatima', name: 'Nova Fatima' },
  { slug: 'nova-laranjeiras', name: 'Nova Laranjeiras' },
  { slug: 'nova-londrina', name: 'Nova Londrina' },
  { slug: 'nova-olimpia', name: 'Nova Olimpia' },
  { slug: 'nova-prata-do-iguacu', name: 'Nova Prata Do Iguacu' },
  { slug: 'nova-santa-barbara', name: 'Nova Santa Barbara' },
  { slug: 'nova-santa-rosa', name: 'Nova Santa Rosa' },
  { slug: 'nova-tebas', name: 'Nova Tebas' },
  { slug: 'novo-itacolomi', name: 'Novo Itacolomi' },
  { slug: 'ortigueira', name: 'Ortigueira' },
  { slug: 'ortigueira-colorado', name: 'Ortigueira Colorado' },
  { slug: 'ourizona', name: 'Ourizona' },
  { slug: 'ouro-verde-do-oeste', name: 'Ouro Verde Do Oeste' },
  { slug: 'paicandu', name: 'Paicandu' },
  { slug: 'palmas', name: 'Palmas' },
  { slug: 'palmeira', name: 'Palmeira' },
  { slug: 'palmital', name: 'Palmital' },
  { slug: 'palotina', name: 'Palotina' },
  { slug: 'paraiso-do-norte', name: 'Paraiso Do Norte' },
  { slug: 'paranacity', name: 'Paranacity' },
  { slug: 'paranagua', name: 'Paranagua' },
  { slug: 'paranapoema', name: 'Paranapoema' },
  { slug: 'paranavai', name: 'Paranavai' },
  { slug: 'pato-bragado', name: 'Pato Bragado' },
  { slug: 'pato-branco', name: 'Pato Branco' },
  { slug: 'paula-freitas', name: 'Paula Freitas' },
  { slug: 'paulo-frontin', name: 'Paulo Frontin' },
  { slug: 'peabiru', name: 'Peabiru' },
  { slug: 'perobal', name: 'Perobal' },
  { slug: 'perola', name: 'Perola' },
  { slug: 'perola-d-oeste', name: 'Perola D Oeste' },
  { slug: 'pien', name: 'Pien' },
  { slug: 'pinhais', name: 'Pinhais' },
  { slug: 'pinhal-de-sao-bento', name: 'Pinhal De Sao Bento' },
  { slug: 'pinhalao', name: 'Pinhalao' },
  { slug: 'pinhao', name: 'Pinhao' },
  { slug: 'pirai-do-sul', name: 'Pirai Do Sul' },
  { slug: 'piraquara', name: 'Piraquara' },
  { slug: 'pitanga', name: 'Pitanga' },
  { slug: 'pitangueiras', name: 'Pitangueiras' },
  { slug: 'planaltina-do-parana', name: 'Planaltina Do Parana' },
  { slug: 'planalto', name: 'Planalto' },
  { slug: 'ponta-grossa', name: 'Ponta Grossa' },
  { slug: 'pontal-do-parana', name: 'Pontal Do Parana' },
  { slug: 'porecatu', name: 'Porecatu' },
  { slug: 'porto-amazonas', name: 'Porto Amazonas' },
  { slug: 'porto-barreiro', name: 'Porto Barreiro' },
  { slug: 'porto-rico', name: 'Porto Rico' },
  { slug: 'porto-vitoria', name: 'Porto Vitoria' },
  { slug: 'prado-ferreira', name: 'Prado Ferreira' },
  { slug: 'pranchita', name: 'Pranchita' },
  { slug: 'presidente-castelo-branco', name: 'Presidente Castelo Branco' },
  { slug: 'primeiro-de-maio', name: 'Primeiro De Maio' },
  { slug: 'prudentopolis', name: 'Prudentopolis' },
  { slug: 'quarto-centenario', name: 'Quarto Centenario' },
  { slug: 'quatigua', name: 'Quatigua' },
  { slug: 'quatro-barras', name: 'Quatro Barras' },
  { slug: 'quatro-pontes', name: 'Quatro Pontes' },
  { slug: 'quedas-do-iguacu', name: 'Quedas Do Iguacu' },
  { slug: 'querencia-do-norte', name: 'Querencia Do Norte' },
  { slug: 'quinta-do-sol', name: 'Quinta Do Sol' },
  { slug: 'quitandinha', name: 'Quitandinha' },
  { slug: 'ramilandia', name: 'Ramilandia' },
  { slug: 'rancho-alegre', name: 'Rancho Alegre' },
  { slug: 'rancho-alegre-d-oeste', name: 'Rancho Alegre D Oeste' },
  { slug: 'realeza', name: 'Realeza' },
  { slug: 'reboucas', name: 'Reboucas' },
  { slug: 'renascenca', name: 'Renascenca' },
  { slug: 'reserva', name: 'Reserva' },
  { slug: 'reserva-do-iguacu', name: 'Reserva Do Iguacu' },
  { slug: 'ribeirao-claro', name: 'Ribeirao Claro' },
  { slug: 'ribeirao-do-pinhal', name: 'Ribeirao Do Pinhal' },
  { slug: 'rio-azul', name: 'Rio Azul' },
  { slug: 'rio-bom', name: 'Rio Bom' },
  { slug: 'rio-bonito-do-iguacu', name: 'Rio Bonito Do Iguacu' },
  { slug: 'rio-branco-do-ivai', name: 'Rio Branco Do Ivai' },
  { slug: 'rio-branco-do-sul', name: 'Rio Branco Do Sul' },
  { slug: 'rio-negro', name: 'Rio Negro' },
  { slug: 'rolandia', name: 'Rolandia' },
  { slug: 'roncador', name: 'Roncador' },
  { slug: 'rondon', name: 'Rondon' },
  { slug: 'rosario-do-ivai', name: 'Rosario Do Ivai' },
  { slug: 'sabaudia', name: 'Sabaudia' },
  { slug: 'salgado-filho', name: 'Salgado Filho' },
  { slug: 'salto-do-itarare', name: 'Salto Do Itarare' },
  { slug: 'salto-do-lontra', name: 'Salto Do Lontra' },
  { slug: 'santa-amelia', name: 'Santa Amelia' },
  { slug: 'santa-cecilia-do-pavao', name: 'Santa Cecilia Do Pavao' },
  { slug: 'santa-cruz-de-monte-castelo', name: 'Santa Cruz De Monte Castelo' },
  { slug: 'santa-fe', name: 'Santa Fe' },
  { slug: 'santa-helena', name: 'Santa Helena' },
  { slug: 'santa-ines', name: 'Santa Ines' },
  { slug: 'santa-isabel-do-ivai', name: 'Santa Isabel Do Ivai' },
  { slug: 'santa-izabel-do-oeste', name: 'Santa Izabel Do Oeste' },
  { slug: 'santa-lucia', name: 'Santa Lucia' },
  { slug: 'santa-maria-do-oeste', name: 'Santa Maria Do Oeste' },
  { slug: 'santa-mariana', name: 'Santa Mariana' },
  { slug: 'santa-monica', name: 'Santa Monica' },
  { slug: 'santa-tereza-do-oeste', name: 'Santa Tereza Do Oeste' },
  { slug: 'santa-terezinha-de-itaipu', name: 'Santa Terezinha De Itaipu' },
  { slug: 'santa-terezinha-do-iguacu', name: 'Santa Terezinha Do Iguacu' },
  { slug: 'santana-do-itarare', name: 'Santana Do Itarare' },
  { slug: 'santo-antonio-da-platina', name: 'Santo Antonio Da Platina' },
  { slug: 'santo-antonio-do-caiua', name: 'Santo Antonio Do Caiua' },
  { slug: 'santo-antonio-do-paraiso', name: 'Santo Antonio Do Paraiso' },
  { slug: 'santo-antonio-do-sudoeste', name: 'Santo Antonio Do Sudoeste' },
  { slug: 'santo-inacio', name: 'Santo Inacio' },
  { slug: 'sao-carlos-do-ivai', name: 'Sao Carlos Do Ivai' },
  { slug: 'sao-jeronimo-da-serra', name: 'Sao Jeronimo Da Serra' },
  { slug: 'sao-joao', name: 'Sao Joao' },
  { slug: 'sao-joao-do-caiua', name: 'Sao Joao Do Caiua' },
  { slug: 'sao-joao-do-ivai', name: 'Sao Joao Do Ivai' },
  { slug: 'sao-joao-do-triunfo', name: 'Sao Joao Do Triunfo' },
  { slug: 'sao-jorge-d-oeste', name: 'Sao Jorge D Oeste' },
  { slug: 'sao-jorge-do-ivai', name: 'Sao Jorge Do Ivai' },
  { slug: 'sao-jorge-do-patrocinio', name: 'Sao Jorge Do Patrocinio' },
  { slug: 'sao-jose', name: 'Sao Jose' },
  { slug: 'sao-jose-da-boa-vista', name: 'Sao Jose Da Boa Vista' },
  { slug: 'sao-jose-das-palmeiras', name: 'Sao Jose Das Palmeiras' },
  { slug: 'sao-jose-dos-pinhais', name: 'Sao Jose Dos Pinhais' },
  { slug: 'sao-manoel-do-parana', name: 'Sao Manoel Do Parana' },
  { slug: 'sao-mateus-do-sul', name: 'Sao Mateus Do Sul' },
  { slug: 'sao-matheus-do-sul', name: 'Sao Matheus Do Sul' },
  { slug: 'sao-miguel-do-iguacu', name: 'Sao Miguel Do Iguacu' },
  { slug: 'sao-pedro-do-iguacu', name: 'Sao Pedro Do Iguacu' },
  { slug: 'sao-pedro-do-ivai', name: 'Sao Pedro Do Ivai' },
  { slug: 'sao-pedro-do-parana', name: 'Sao Pedro Do Parana' },
  { slug: 'sao-sebastiao-da-amoreira', name: 'Sao Sebastiao Da Amoreira' },
  { slug: 'sao-tome', name: 'Sao Tome' },
  { slug: 'sapopema', name: 'Sapopema' },
  { slug: 'sarandi', name: 'Sarandi' },
  { slug: 'saudade-do-iguacu', name: 'Saudade Do Iguacu' },
  { slug: 'senges', name: 'Senges' },
  { slug: 'serranopolis-do-iguacu', name: 'Serranopolis Do Iguacu' },
  { slug: 'sertaneja', name: 'Sertaneja' },
  { slug: 'sertanopolis', name: 'Sertanopolis' },
  { slug: 'siqueira-campos', name: 'Siqueira Campos' },
  { slug: 'sulina', name: 'Sulina' },
  { slug: 'tamarana', name: 'Tamarana' },
  { slug: 'tamboara', name: 'Tamboara' },
  { slug: 'tapejara', name: 'Tapejara' },
  { slug: 'tapira', name: 'Tapira' },
  { slug: 'teixeira-soares', name: 'Teixeira Soares' },
  { slug: 'telemaco-borba', name: 'Telemaco Borba' },
  { slug: 'terra-boa', name: 'Terra Boa' },
  { slug: 'terra-rica', name: 'Terra Rica' },
  { slug: 'terra-roxa', name: 'Terra Roxa' },
  { slug: 'thopinzinho', name: 'Thopinzinho' },
  { slug: 'tibagi', name: 'Tibagi' },
  { slug: 'tijucas-do-sul', name: 'Tijucas Do Sul' },
  { slug: 'toledo', name: 'Toledo' },
  { slug: 'tomazina', name: 'Tomazina' },
  { slug: 'tres-barras-do-parana', name: 'Tres Barras Do Parana' },
  { slug: 'tunas-do-parana', name: 'Tunas Do Parana' },
  { slug: 'tuneiras-do-oeste', name: 'Tuneiras Do Oeste' },
  { slug: 'tupassi', name: 'Tupassi' },
  { slug: 'turvo', name: 'Turvo' },
  { slug: 'ubirata', name: 'Ubirata' },
  { slug: 'umuarama', name: 'Umuarama' },
  { slug: 'uniao-da-vitoria', name: 'Uniao Da Vitoria' },
  { slug: 'uniflor', name: 'Uniflor' },
  { slug: 'urai', name: 'Urai' },
  { slug: 'ventania', name: 'Ventania' },
  { slug: 'vera-cruz-do-oeste', name: 'Vera Cruz Do Oeste' },
  { slug: 'vere', name: 'Vere' },
  { slug: 'virmond', name: 'Virmond' },
  { slug: 'vitorino', name: 'Vitorino' },
  { slug: 'wenceslau-braz', name: 'Wenceslau Braz' },
  { slug: 'xambre', name: 'Xambre' },
] as const

export type City = (typeof citiesPR)[number]

export function getCityBySlug(slug: string) {
  return citiesPR.find(c => c.slug === slug)
}
